version: '3.8'

services:

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/casino_game_lobby

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/casino_game_lobby
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
